name: haberApp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.1+2
  cupertino_icons: ^1.0.0
  http:
  path:
  xml:
  url_launcher: ^5.7.10
  webfeed: ^0.6.0
  cached_network_image: ^1.0.0
  provider: ^4.3.2+3
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
assets:
  - images/
  - videos/
  - files/
  - assets/images/google-logo.png
